// lib/email/templates/job-application.tsx
export function jobApplicationHtml({ employer_name, alumni_name, job_title, applied_at, applicants_url }: { employer_name: string; alumni_name: string; job_title: string; applied_at: string; applicants_url: string }): string {
  return `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f0f4f8;font-family:Arial,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 0;"><tr><td align="center"><table width="580" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#1e3a5f,#2d5a27);padding:40px;text-align:center;"><h1 style="margin:0;color:#fff;font-size:20px;">New Job Application 📋</h1></td></tr><tr><td style="padding:40px;"><p style="color:#4a5568;font-size:15px;line-height:1.7;">Dear <strong>${employer_name}</strong>,</p><p style="color:#4a5568;font-size:15px;line-height:1.7;"><strong>${alumni_name}</strong> has applied for your posting: <strong>${job_title}</strong></p><p style="color:#718096;font-size:13px;">Applied: ${applied_at}</p><div style="text-align:center;margin:24px 0;"><a href="${applicants_url}" style="background:#1e3a5f;color:#fff;text-decoration:none;padding:12px 32px;border-radius:8px;font-size:15px;">View Application →</a></div></td></tr><tr><td style="background:#f7fafc;padding:20px;border-top:1px solid #e2e8f0;text-align:center;"><p style="margin:0;color:#718096;font-size:13px;">© ${new Date().getFullYear()} Polytechnic College of La Union · AICTS</p></td></tr></table></td></tr></table></body></html>`;
}

export function applicationStatusHtml({ alumni_name, job_title, company_name, status, jobs_url }: { alumni_name: string; job_title: string; company_name: string; status: string; jobs_url: string }): string {
  const statusColors: Record<string, string> = { shortlisted: '#2d7d32', for_interview: '#1e3a5f', hired: '#276749', rejected: '#c53030', viewed: '#4a5568' };
  const color = statusColors[status] ?? '#4a5568';
  const statusLabels: Record<string, string> = { shortlisted: 'Shortlisted', for_interview: 'For Interview', hired: 'Hired! 🎉', rejected: 'Not Shortlisted', viewed: 'Application Viewed' };
  return `<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f0f4f8;font-family:Arial,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 0;"><tr><td align="center"><table width="580" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;"><tr><td style="background:${color};padding:40px;text-align:center;"><h1 style="margin:0;color:#fff;font-size:20px;">Application Status Update</h1></td></tr><tr><td style="padding:40px;"><p style="color:#4a5568;font-size:15px;">Dear <strong>${alumni_name}</strong>,</p><p style="color:#4a5568;font-size:15px;line-height:1.7;">Your application for <strong>${job_title}</strong> at <strong>${company_name}</strong> has been updated to: <span style="color:${color};font-weight:700;">${statusLabels[status] ?? status}</span></p><div style="text-align:center;margin:24px 0;"><a href="${jobs_url}" style="background:#1e3a5f;color:#fff;text-decoration:none;padding:12px 32px;border-radius:8px;font-size:15px;">View My Applications →</a></div></td></tr><tr><td style="background:#f7fafc;padding:20px;border-top:1px solid #e2e8f0;text-align:center;"><p style="margin:0;color:#718096;font-size:13px;">© ${new Date().getFullYear()} Polytechnic College of La Union · AICTS</p></td></tr></table></td></tr></table></body></html>`;
}
